/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mimiro.datahub.clientsdk;

import org.junit.Test;
import static org.junit.Assert.*;

public class ClientTest {
    @Test
    public void testCreateClient() {
        DatahubClient client = new DatahubClient();
        assertNotNull("client should not be null", client);
    }
}
